1626221949647	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1626222279701	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1626222279702	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1626222279710	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1626222279714	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1626222879712	Sync.Service	DEBUG	User-Agent: Firefox/78.11.0 (Linux x86_64) FxSync/1.80.0.20210531140902.desktop
1626222879712	Sync.Service	INFO	Starting sync at 2021-07-14 10:34:39 in browser session ZUQImpKdXDFJ
1626222879713	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1626222879726	Sync.Status	INFO	Resetting Status.
1626222879726	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1626222879728	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1626222879728	FirefoxAccounts	DEBUG	getOAuthToken enter
1626222879730	FirefoxAccounts	TRACE	getCachedToken returning cached token
1626222879730	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1626222879730	Sync.BrowserIDManager	INFO	Getting keys
1626222879731	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1626222879734	Sync.BrowserIDManager	INFO	Getting an assertion from: https://token.services.mozilla.com/1.0/sync/1.5
1626222879734	FirefoxAccounts	DEBUG	enter getAssertion()
1626222879735	FirefoxAccounts	DEBUG	getKeypairAndCertificate: already have keyPair and certificate
1626222879735	FirefoxAccounts	DEBUG	getAssertionFromCert
1626222879739	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1626222879740	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1626222879740	FirefoxAccounts	DEBUG	getAssertionFromCert returning signed: true
1626222879740	Sync.BrowserIDManager	DEBUG	Getting a token using an Assertion
1626222879740	Services.Common.TokenServerClient	DEBUG	Beginning BID assertion exchange: https://token.services.mozilla.com/1.0/sync/1.5
1626222879741	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1626222879744	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1626222879744	Sync.BrowserIDManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
_tokenServerExchangeRequest@tokenserverclient.js:298:13
1626222879745	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1626222879745	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1626222879745	Sync.BrowserIDManager	ERROR	Failed to fetch a token for authentication: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
_tokenServerExchangeRequest@tokenserverclient.js:298:13
1626222879747	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1626222879751	Sync.BulkKeyBundle	INFO	BulkKeyBundle being created for undefined
1626222879752	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/166986188/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1626222879752	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1626222879752	Sync.Status	DEBUG	Status.service: error.login.failed => error.sync.failed
1626222879753	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1626222879753	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1626222879757	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
